title: Shortie Data
description: A blog on data and climbing

url: https://euranofshin.github.io/shortiedata/
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

# One pitch at a time
# Pitch by pitch
# data to beta
# More than a grade
# The Crux of the Matter
# The [] Crux
# Chalk it up (to data?)
# Gradient Ascent
# Computable Crux
#
# Climbing words: crux, pump, chalk, exposure
navigation:
    - title: Home
      url: /index.html
        #    - title: All Posts
        #      url: /all
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    github: euranofshin
    email: shortiedata@gmail.com

google_analytics: "G-EMCDHHNR1K"

disqus:
    shortname: euranofshin
