title: Shortie Data
description: Long Form Jekyll theme built with SASS

url: https://long-haul.netlify.app
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

# One pitch at a time
# Pitch by pitch
# data to beta
# More than a grade
# The Crux of the Matter
# The [] Crux
# Chalk it up (to data?)
# Gradient Ascent
# Computable Crux
#
# Climbing words: crux, pump, chalk, exposure
navigation:
    - title: Home
      url: /index.html
        #    - title: All Posts
        #      url: /all
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    github: brianmaierjr
    twitter: brianmaierjr
    facebook: brianmaierjr
    email: brimaidesigns@gmail.com
    linkedin: brianmaierjr
    youtube: RickAstleyYT
    tumblr: i-am-a-fish

google_analytics: "UA-58263416-1"

disqus:
    shortname: euranofshin
